### ISSUE TITLE
What is the licence? 

### ISSUE THREAD

**Issue by PetterSunnyVR** [lordjesus/Packt-Introduction-to-graph-algorithms-for-game-developers#1]
Hi. I have followed your course on packtpub. Can I use your scripts in my own projects?
Thanks!

**Comment by lordjesus** [comment]
Hi Petter,

I've asked Packt about the license. Their reply:

> Paid readers can use example code and instruction as freely, inclusive of in commercial projects with the exception that they not be a reproduction of the entire example application(s) created in the Book or Video and then be sold commercially. You may also not reproduce the actual written or video instruction itself as per Copyright law.
> 
> Our code is released as Open Source.
> 
> So as an example, if you are following along with one of our Untiy books and reproduce the example game in the book you cannot resell that game but you can release it under the same terms, i.e. Open Source.
> 
> If you used excerpts or functions from that book to create your own game, i.e. a game that does not resemble the example game but has similar functionality and/or uses part of the code, then that can be released and sold by the reader."
> 
> You can also click on the below link for the Packt terms and condition
>  
> https://www.packtpub.com/in/about/terms-and-conditions

> 
> *Terms*
> 
> License to use Packt
> Packt grants PacktPub.com account holders a limited license to access free content on Packt and paid subscribers access to agreed content, for personal or business use as per your agreement, but not to modify or re-use its contents, or any portion of it, except with express written consent of Packt. Packt retains the right to remove access to free content. When any paid subscription period ends, unlimited access to content is removed and any caching must be removed. This does not affect any free, downloaded or individually purchased content outside of a subscription.
> This is providing he has purchased the product or has a subscription.

I hope this answers your question.
